### ISSUE TITLE
Allow to be used through `loaders` too?

### ISSUE THREAD

**Issue by bebraw** [webpack/extract-text-webpack-plugin#103]
Interestingly

> loader: ExtractTextPlugin.extract('style', 'css'),

works but

> loaders: [ExtractTextPlugin.extract('style', 'css')],

doesn't. Any idea why?

**Comment by CtrlZvi** [comment]
@bebraw What's the error you're seeing? Is it a module parse failure? If so, I believe it's because ExtractTextPlugin.extract() returns a module chain as a string, meaning it has a "!" in it. Because `loaders` doesn't treat the elements of the array as a module chain, it doesn't split them on "!".

Try instead `loaders: ExtractTextPlugin.extract('style', 'css').split('!')`

**Comment by bebraw** [comment]
@CtrlZvi I don't remember the error but what you just said explains what's going on perfectly. Thanks!

**Comment by CtrlZvi** [comment]
I've run into a further problem I haven't tracked the cause of yet, where the format of the string returned by extract is very different if it's called on an instance.

**Comment by bebraw** [comment]
@CtrlZvi Maybe you are hitting [the else branch](https://github.com/webpack/extract-text-webpack-plugin/blob/dc353ee5791b5ece9488d8321c79d89b0d806984/index.js#L163) then? Can you set up a little demo illustrating the issue?

**Comment by CtrlZvi** [comment]
@bebraw I think you're right, and I was hitting the else branch. When I made #112 I didn't realize .extract was specified both on the prototype and on the object itself. So I only fixed the one on the object, and that's why the instance doesn't work for me..

**Comment by ianwalter** [comment]
@bebraw Can this be closed?

**Comment by bebraw** [comment]
@ianwalter Totally forgot about this. Closed.
