### ISSUE TITLE
Support webpack 2.2

### ISSUE THREAD

**Issue by Strate** [webpack/extract-text-webpack-plugin#309]
Seems that plugin should be published with updated peer dependencies

**Comment by MikeLP** [comment]
Guys. It is really hard to update package.json ?

**Comment by avetisk** [comment]
Really need this update :'(

Christmas is like hell for developers who are still working...

**Comment by laggingreflex** [comment]
Try `npm update` or `npm clear cache`.  Semver allows updating to latest minor versions (for >1.x). So v2.1 should really install v2.2 if that's the latest one available, given that it's not using the cache.

**Comment by aaugustin** [comment]
Can we avoid non-constructive comments? They're unlikely to motivate maintainers, on the contrary. If I was receiving such comments on one of my repositories, I'd make sure not to fix the issue for a month or two :-) Thanks!

**Comment by aaugustin** [comment]
(Obviously this wasn't for laggingreflex. I wrote my comment before theirs appeared.)

**Comment by TheLarkInn** [comment]
@MikeLP Sorry for the delay on this. There are some overall large changes we want to make here before we do another publish. There is a lot of tenderloving care that needs to be given to this repo. We have already extended the call for extra support for issues and PR's to our @webpack/contributor-team so once we get some more information, we'll have some folks getting back to you guys. 

Understand the frustration, and we apologize for dropping the ball. Thank you everyone for the support, and if it is possible you can avoid the PeerDep and install fails by using npm v3 for now! Let me know if anything else needs to be clarified.

**Comment by Strate** [comment]
I use shrinkwrap feature of npm. It requires me to satisfy all peer dependencies.

**Comment by btipling** [comment]
@TheLarkInn, thanks for the update, but can you please update the peer dependency to not require the beta though? Some people cannot deploy with yarn/npm warnings because of how ops has configured their ci deploy system with fail on warnings. We cannot move beyond `webpack@^2.1.0-beta.19` because [you hardcoded beta as a peerDependency](https://github.com/webpack/extract-text-webpack-plugin/blob/master/package.json#L25). We're trying to use the `"2.2.0-rc` now but can't. You can use a more lenient dependency rule. It's a one line change that would stop blocking us. Please if you can, thank you and thank you for all your hard work on this great plugin!

**Comment by Tibfib** [comment]
Looks like a fix to that has been committed: https://github.com/webpack/extract-text-webpack-plugin/commit/cbd4690856707cbaaade1e960bfb2aef044cdeb3.

Here's to hoping it'll be released soon...

**Comment by dawncold** [comment]
I install latest code via git+https: `npm install git+https://github.com/webpack/extract-text-webpack-plugin.git -D`

**Comment by lvchangqi** [comment]
the code in npm haven't been updated  :(

**Comment by SpaceK33z** [comment]
Fix was published in `extract-text-webpack-plugin@2.0.0-beta.5`.
